theme: jekyll-theme-architect
github:
  zip_url: https://github.com/Tech-Overlord/system-info/releases/download/v1.0.0/system-info-1.0.0.zip
  tar.gz_url: https://github.com/Tech-Overlord/system-info/releases/download/v1.0.0/system-info-1.0.0.tar.gz